WMO_CODES = {
    0:  {"emoji": "☀️",  "desc": "Clear sky"},
    1:  {"emoji": "🌤️", "desc": "Mainly clear"},
    2:  {"emoji": "⛅",  "desc": "Partly cloudy"},
    3:  {"emoji": "☁️",  "desc": "Overcast"},
    45: {"emoji": "🌫️", "desc": "Fog"},
    48: {"emoji": "🌫️❄️", "desc": "Depositing rime fog"},
    51: {"emoji": "🌦️", "desc": "Drizzle (light)"},
    53: {"emoji": "🌦️", "desc": "Drizzle (moderate)"},
    55: {"emoji": "🌧️", "desc": "Drizzle (dense)"},
    56: {"emoji": "🌧️❄️", "desc": "Freezing drizzle (light)"},
    57: {"emoji": "🌧️❄️", "desc": "Freezing drizzle (dense)"},
    61: {"emoji": "🌧️", "desc": "Rain (slight)"},
    63: {"emoji": "🌧️", "desc": "Rain (moderate)"},
    65: {"emoji": "🌧️", "desc": "Rain (heavy)"},
    66: {"emoji": "🌧️❄️", "desc": "Freezing rain (light)"},
    67: {"emoji": "🌧️❄️", "desc": "Freezing rain (heavy)"},
    71: {"emoji": "🌨️", "desc": "Snowfall (slight)"},
    73: {"emoji": "🌨️", "desc": "Snowfall (moderate)"},
    75: {"emoji": "🌨️", "desc": "Snowfall (heavy)"},
    77: {"emoji": "❄️",  "desc": "Snow grains"},
    80: {"emoji": "🌦️", "desc": "Rain showers (slight)"},
    81: {"emoji": "🌧️", "desc": "Rain showers (moderate)"},
    82: {"emoji": "🌧️🌩️", "desc": "Rain showers (violent)"},
    85: {"emoji": "🌨️", "desc": "Snow showers (slight)"},
    86: {"emoji": "🌨️", "desc": "Snow showers (heavy)"},
    95: {"emoji": "⛈️", "desc": "Thunderstorm (slight or moderate)"},
    96: {"emoji": "⛈️🌨️", "desc": "Thunderstorm with slight hail"},
    99: {"emoji": "⛈️🌨️", "desc": "Thunderstorm with heavy hail"},
}
